services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URI: postgresql+asyncpg://app_user:app_password@postgres:5432/app_db
    ports:
      - "5001:5001"

volumes:
  postgres_data:
